name: Minor Version Bump

on:
  workflow_dispatch:
  #pull_request:
#    branches: [main]
#    types: [closed]
  push:
    branches: [main]
    runs-on: [minor]
jobs:
  version_bump:
    runs-on: ubuntu-latest
#    if: ${{ github.event.pull_request.merged == true }}
    env:
      working-directory: .github
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1.7.3
        with:
          configuration: ".github/changelog_configuration.json"
          ignorePreReleases: "false"
          toTag: ${{ steps.tag_version.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{steps.build_changelog.outputs.changelog}}
