name: npx test

on:
  push:
    branches: [main]
jobs:
  validate_json_with_schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate json with schema
        run: ls -la
