name: npx test

on:
  push:
    branches: [main]
jobs:
  validate_json_with_schema:
    runs-on: ubuntu-latest
    steps:
      - name: Validate json with schema
        run: npx ajv-cli -s workflow-schema.json -d sample.json
