name: Version Bump

on:
  workflow_dispatch:
  pull_request:
   branches: [main]
   types: [closed]
#  push:
#    branches: [main]
jobs:
#  get_bump_level:
#    runs-on: ubuntu-latest
#    outputs:
#      bump_level: ${{ steps.step1.outputs.bump_level }}
#    steps:
#      - id: step1
#        run: echo "::set-output name=bump_level::$(gh pr view PR_NUMBER --json labels --jq '.labels[].name')"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PR_NUMBER: ${{ github.event.pull_request.number }}
  version_bump:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    env:
      working-directory: .github
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - uses: actions/checkout@v2
      - name: Get bump level

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1.7.3
        with:
          configuration: ".github/changelog_configuration.json"
          ignorePreReleases: "false"
          toTag: ${{ steps.tag_version.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{steps.build_changelog.outputs.changelog}}
